import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SearchBar from './SearchBar'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Search APP</title>
      </Head>
      <header className="bg-gray-800 text-white">
        <div className="max-w-screen-lg mx-auto py-4 px-6 flex items-center justify-between">
          <h1 className="text-2xl font-bold">Search APP</h1>
        </div>
      </header>
      <main className="flex-grow">{children}</main>
      <footer className="bg-gray-800 text-white py-4">
        <div className="max-w-screen-lg mx-auto px-6">
          <p className="text-center">&copy; Sebastian Garay {new Date().getFullYear()}</p>
        </div>
      </footer>
    </div>
  );
};